---
version: "1.0.4"
slug: "mediatracker"
name: "MediaTracker"
description: "Self-hosted media tracker for movies and TV shows"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
init: false
boot: "auto"
ports:
  4020/tcp: 7481
options:
  port: 4020
schema:
  port: int
map:
  config: true
command: ["/bin/bash", "/app/run.sh"]
