---
version: "1.0.8"
slug: "mediatracker"
name: "MediaTracker"
description: "Self-hosted media tracker for movies, TV shows, books, audiobooks and games.(8)"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
init: false
boot: "auto"
ports:
  7481/tcp: NULL
ports_description:
  7481/tcp: Web interface
map:
  config: true
  ssl: false
  data: true
command: ["/bin/bash", "/app/run.sh"]
