---
version: "1.0.6"
slug: "mediatracker"
name: "MediaTracker"
description: "Self-hosted media tracker for movies and TV shows"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
init: false
boot: "auto"
ports:
  7481/tcp: NULL
ports_description:
  7481/tcp: Web interface
map:
  config: true
command: ["/bin/bash", "/app/run.sh"]
